travis:
  secure:
    BINSTAR_TOKEN: KI6DLiuL43BlGPb1iOMWxjhRUTZwbREoYYBir+QyuqToaXSzeXnResKP7dupYbpiBSCFdxYixfAWPHRxZED7uKE2kagu1EOilQ3hVrbqN490O/JxIlJeMC5Dra2MtWat7Zufd+ZiT0e9oJohmO4NE4C80a/Y23lrMirzA97yQWs4f6iOGv69yMbjLvajiYtHZftHSDPdZRyUxQBkDPNauZUQlxKH8RDsf7i7Ms22qT/45I4re8xZQYEgsK6fQg1/zBQcAF7tPNZHaQTXFRMsuUYDItTjuKAJj35gJhbqRvOSlH2bP0O4RTYaEsR9t2k/ktmG8E9P3A0vhEz6npZhZ3mmCEjk3/QMjBgzAXa3aOGX8WC6Y7csJEN9rPYfwqdG2MlF49w8qfjamhqwEkIyHV5mb/almsM4Jiv1g2kNtu4IMD+SNkGeuueOJm50g4LGbTP5SosEBG24yPzK9Gj6j3xnCMW68bU8AKdxReJ68nLkN3d2e+Tu3IZ+fsZE1xeYiE5ktYNmLnQOZVw5+vZMA1eTgS2eoMf5JaKvINg0X1uQ/ux8pvFF8Rxw+yxNhRkx+tyToEfCATZ7Vw7x1Iwu4I5fWIa0iMFHtUQoG7fIryb2PGZ/hJuhvnMc64kossrMubzmQC2IZA8U1175BL5LJTORmaOaUdT8dmen2muU1i4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
