travis:
  secure:
    BINSTAR_TOKEN: OoMe2ljCvp5Y00qrSGzHmJO1ENvVlChHcuO6OWOELTxOzewR0JzJq9OpH6OOXjcL3ceX3P0BJGXi2kx+Ax90TST4bHdFIjmrRNrL2PKnSZJ8K1CzhgUbMDrO4aH93CbpX6zILMq57J0rFlO5wKn0lEdMyGOGL1PtiOceqYixHUJxJLqOwl0SKDsAy2IMhdY2QTdut+fGi/f4qzTE2Ffd1rdjlkjrrqnvFZSVlxylPcfByN36rLoZunShIbwJqZnMrYXqAxjraJNBY2VILZzrNFbsHH/BGLKG93L4PHo3GH23iFeLSe5OfawcEcCmI8XYAbANFQ07Hc9wW8CLglqvaIPZzYFy1gd+n4goOUCevMbsM6esVR6s4r8ZfCoXV8gp5wcz9sy7++9RKBRvcgoSPWDiGl2VUIu3MHOnxwtb74gLoTS394tavle/VoAkGkygVym60ieaRVK4EdKRmT5EmIXEvyiQPThULwlhpfby4S0OLPnZOPrMwyQnNwcw91RtyoM+4qAuqMbZUZWtP8cEAASKtB4w4dEzgqk2NpKYpHA/+aBjmZ/OqdlJZnvXXDS8qynSJ1ghJr3i0RNAyPaQ7Z8iDW8cNIDvUlxlChjm6wzpTbnkUHH+gvDOa7VdTldl/jTHLot1kW510CTyXBoaXb98u3TehziJliYbqbPQR7M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
